CC=g++

all: pointer memory lifetimes dynamic

pointer: pointer.cpp
	$(CC) pointer.cpp -o pointer

memory: memory.cpp
	$(CC) memory.cpp -o memory

lifetimes: lifetimes.cpp
	$(CC) lifetimes.cpp -o lifetimes

dynamic: dynamic.cpp
	$(CC) dynamic.cpp -o dynamic

clean:
	rm -f pointer memory lifetimes dynamic
