CC=g++

all: pointer memory lifetimes dynamic references linked_list_example

pointer: pointer.cpp
	$(CC) pointer.cpp -o pointer

memory: memory.cpp
	$(CC) memory.cpp -o memory

lifetimes: lifetimes.cpp
	$(CC) lifetimes.cpp -o lifetimes

dynamic: dynamic.cpp
	$(CC) dynamic.cpp -o dynamic

references: references.cpp
	$(CC) references.cpp -o references

linked_list_example: linked_list_example.cpp
	$(CC) linked_list_example.cpp -o linked_list_example

clean:
	rm -f pointer memory lifetimes dynamic references linked_list_example
